# PvP Toggle by @brokiem (github.com/brokiem/PvPToggle)

# Save pvptoggle data to file in seconds
# Incrase this value if your server lags every 5 minutes
# Default: 600
save.data.delay: 600

# Enable pvp on default setting/new player
default.pvp: off

# Messages
pvp.activated: "&aPvP Mode Activated!"
pvp.deactivated: "&cPvP Mode Deactivated!"

staff.pvp.activated: "&aSuccessful activated {name} PvP Mode!"
staff.pvp.deactivated: "&eSuccessful deactivated {name} PvP Mode!"

pvp.is.activated.damager: "&eYou haven't activated pvp mode"
pvp.is.activated.entity: "&6{name} &ehaven't activated pvp mode"